version: '3.8'

services:
  app:
    build: .
    image: elyza-tasks-100:latest
    volumes:
      - ./output:/app/output
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
